title:   Ilia Skripko
logo: "images/IMG_20220525_180815_079.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  An aspiring data and business intelligence analyst with a background in health sciences, finance, and commercial banking.  Proficient in SQL, Python, Tableau, and Power BI, with the ability to extract and query large datasets in order to export it into business intelligence tools for the purpose of attaining relevant data to present to stakeholders and improve business operations using informative dashboards and excellent communication skills. Excelling at problem solving, analyzing data, and identifying opporunities to meet the needs of internal and external stakeholders.
  <br><br>
  <a href="https://www.linkedin.com/in/ilia-skripko/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/profile/shuchang.liang#!/">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/iliaskripko/Portfolio-Ilia-Skripko-642b6a8b9427494b808fde483a4b94c7">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
